function section(number, label, title, description, body) {
  return `<section class="section"><div class="section-head"><div><span class="section-no">${number} / ${label}</span><h2>${title}</h2></div><p>${description}</p></div>${body}</section>`;
}

const responsiveHtml = `<main class="page docs-page">
<header class="page-head"><div><span class="eyebrow">CIIMO / documentação / responsividade</span><h1>Mobile primeiro na composição.</h1><p>O conteúdo continua claro em telas estreitas sem reproduzir a densidade do desktop. A topbar mantém contexto e ações; a sidebar vira drawer; o conteúdo prioriza uma coluna e rolagem horizontal fica restrita aos dados que realmente precisam manter largura.</p></div><div class="page-index">01 — Shell<br>02 — Layout<br>03 — Dados<br>04 — Previews<br>05 — Toque<br>06 — Teste</div></header>
${section('01', 'Shell', 'Topbar fixa, sidebar como drawer', 'Até 760 px, a barra superior permanece visível com menu, breadcrumb, GitHub e tema. O menu lateral sai da composição e abre sobre o conteúdo com backdrop, botão fechar e Escape.', `<div class="grid grid-3"><div class="metric"><small>Topbar</small><strong>64 px</strong><span>Contexto + ações</span></div><div class="metric"><small>Drawer</small><strong>até 292 px</strong><span>86vw máximo</span></div><div class="metric"><small>Conteúdo</small><strong>100%</strong><span>Sem faixa lateral</span></div></div>`)}
${section('02', 'Layout', 'Uma coluna é o padrão', 'Grades de documentação, formulários, pricing, checkout, anatomy e cards não mantêm colunas desktop quando isso comprime a leitura.', `<div class="grid grid-3"><article class="specimen"><span class="variant-title">Página</span><h3>16 px nas laterais</h3><p>O eixo horizontal usa o token de 16 px.</p></article><article class="specimen"><span class="variant-title">Seções</span><h3>24 px no eixo vertical</h3><p>O ritmo continua usando a escala aprovada.</p></article><article class="specimen"><span class="variant-title">Grid</span><h3>1 coluna</h3><p>Duas colunas só permanecem quando o conteúdo é realmente compacto e legível.</p></article></div>`)}
${section('03', 'Dados', 'Rolagem só quando preservar largura é necessário', 'Tabela e fluxo financeiro podem precisar de largura intrínseca. Nesses casos, o container rola horizontalmente; a página inteira nunca deve estourar.', `<div class="icon-rule-list"><div><strong>Tabelas</strong><span><code>overflow-x: auto</code> no wrapper; células não são esmagadas.</span></div><div><strong>Fluxo financeiro</strong><span>Meses continuam lado a lado dentro de uma área rolável.</span></div><div><strong>Tabs</strong><span>Rolagem horizontal com padding de 16 px para não cortar o primeiro ou último item.</span></div><div><strong>Página</strong><span>Não usar scroll horizontal global para esconder problemas de layout.</span></div></div>`)}
${section('04', 'Previews', 'O specimen precisa mostrar a tela, não a moldura desktop', 'Em previews compostos, a sidebar interna é removida no mobile e o conteúdo ocupa a largura disponível. Phone previews continuam limitados à largura realista do aparelho.', `<div class="grid grid-2"><article class="specimen"><span class="variant-title">Mini shell</span><h3>Sidebar interna oculta</h3><p>Evita que uma coluna de navegação comprima o conteúdo demonstrado.</p></article><article class="specimen"><span class="variant-title">Phone</span><h3>Máximo de 390 px</h3><p>Centralizado e limitado pela própria largura da viewport.</p></article></div>`)}
${section('05', 'Toque', 'Interação continua confortável', 'A redução visual não pode reduzir a área de toque. Controles interativos mantêm pelo menos 44 px de altura.', `<div class="grid grid-3"><div class="metric"><small>Botões</small><strong>≥ 44 px</strong></div><div class="metric"><small>Topbar</small><strong>≥ 44 px</strong></div><div class="metric"><small>Links do menu</small><strong>48 px</strong></div></div>`)}
${section('06', 'Teste', 'Verificar a faixa móvel inteira', 'A revisão precisa cobrir telefones pequenos, tamanhos atuais e o limite do breakpoint antes de considerar a página responsiva.', `<div class="cluster"><span class="chip">320 px</span><span class="chip">360 px</span><span class="chip">390 px</span><span class="chip">430 px</span><span class="chip">760 px</span></div><div class="alert" style="margin-top:24px">Critério: sem conteúdo cortado, drawer sobreposto sem consumir a largura do conteúdo, topbar legível, sem grid comprimido, sem texto menor que o necessário e sem scroll horizontal fora de tabelas, tabs ou dados largos.</div>`)}
</main>`;

const responsivePage = {
  route: 'getting-started/responsive.html',
  page: { title: 'Responsividade · CIIMO Design System', html: responsiveHtml },
};

module.exports = { responsivePage };
