function section(number, label, title, description, body) {
  return `<section class="section"><div class="section-head"><div><span class="section-no">${number} / ${label}</span><h2>${title}</h2></div><p>${description}</p></div>${body}</section>`;
}

const themeHtml = `<main class="page docs-page">
<header class="page-head"><div><span class="eyebrow">CIIMO / marca / tema</span><h1>Light e Dark.</h1><p>Os dois temas usam a mesma identidade CIIMO e a mesma hierarquia. O tema altera tokens semânticos de superfície, texto, borda e estados; não altera a cor principal da marca.</p></div><div class="page-index">01 — Princípio<br>02 — Tokens<br>03 — Marca<br>04 — Comportamento</div></header>
${section('01', 'Princípio', 'Dois temas, uma identidade', 'Dark continua sendo a apresentação padrão da CIIMO. Light é uma variante completa de superfície, não uma inversão automática ou filtro sobre o layout.', `<div class="theme-preview-grid"><article class="theme-preview theme-preview--dark"><span class="eyebrow">DARK</span><img src="../assets/brand/ciimo_cw.svg" alt="CIIMO branca com II verde"><div class="theme-preview__surface"><small>Carteira</small><strong>R$ 4,02 mi</strong><span>+12,8% de valorização</span></div></article><article class="theme-preview theme-preview--light"><span class="eyebrow">LIGHT</span><img src="../assets/brand/ciimo_cb.svg" alt="CIIMO preta com II verde"><div class="theme-preview__surface"><small>Carteira</small><strong>R$ 4,02 mi</strong><span>+12,8% de valorização</span></div></article></div>`)}
${section('02', 'Tokens', 'Tema muda significado, não componente', 'Componentes devem consumir tokens semânticos. Evite cores fixas para fundo, superfície, texto e borda fora de specimens que demonstram uma cor específica.', `<div class="table-wrap"><table><thead><tr><th>Token</th><th>Dark</th><th>Light</th><th>Uso</th></tr></thead><tbody><tr><td><strong>background</strong></td><td>#000000</td><td>#F4F1EA</td><td>Canvas principal</td></tr><tr><td><strong>surface</strong></td><td>#0B0B0B</td><td>#FFFFFF</td><td>Cards e blocos principais</td></tr><tr><td><strong>soft</strong></td><td>#111111</td><td>#ECE8DF</td><td>Inputs, chips e superfícies secundárias</td></tr><tr><td><strong>raised</strong></td><td>#181818</td><td>#E2DED5</td><td>Nível elevado sem sombra</td></tr><tr><td><strong>text</strong></td><td>#F4F1EA</td><td>#111111</td><td>Texto principal</td></tr><tr><td><strong>muted</strong></td><td>rgba(244,241,234,.72)</td><td>rgba(17,17,17,.68)</td><td>Texto secundário</td></tr><tr><td><strong>border</strong></td><td>rgba(255,255,255,.12)</td><td>rgba(17,17,17,.14)</td><td>Divisores e contornos</td></tr><tr><td><strong>accent</strong></td><td>#D4FB00</td><td>#D4FB00</td><td>Marca, seleção e ação principal</td></tr></tbody></table></div>`)}
${section('03', 'Marca', 'SVG correto para cada contraste', 'Os arquivos-mestre enviados para a marca são usados diretamente. Não aplicar filter, invert ou recoloração via CSS no logotipo.', `<div class="grid grid-2"><article class="specimen"><span class="variant-title">Dark</span><h3>Assinatura</h3><code>ciimo_cw.svg</code><h3 style="margin-top:16px">Símbolo compacto</h3><code>ii_v.svg</code></article><article class="specimen"><span class="variant-title">Light</span><h3>Assinatura</h3><code>ciimo_cb.svg</code><h3 style="margin-top:16px">Símbolo compacto</h3><code>ii_b.svg</code></article></div>`)}
${section('04', 'Comportamento', 'Preferência persiste entre rotas e sessões', 'A troca acontece no shell independente da sidebar e não remonta o conteúdo. A preferência é salva localmente para permanecer depois de fechar e abrir o navegador.', `<div class="icon-rule-list"><div><strong>Padrão inicial</strong><span>Dark quando ainda não existe preferência salva.</span></div><div><strong>Persistência</strong><span><code>localStorage["ciimo-theme"]</code> com os valores <code>dark</code> ou <code>light</code>.</span></div><div><strong>Sem flash</strong><span>O tema salvo é aplicado no <code>&lt;head&gt;</code> antes do carregamento dos estilos.</span></div><div><strong>Controle</strong><span>Hugeicons <code>sun-03</code> no Dark e <code>moon-02</code> no Light. O botão informa a ação por <code>aria-label</code>.</span></div><div><strong>Regra</strong><span>Qualquer nova superfície precisa funcionar nos dois temas no mesmo commit em que for adicionada à documentação.</span></div></div>`)}
</main>`;

const themePage = {
  route: 'brand/theme.html',
  page: {
    title: 'Tema claro e escuro · CIIMO Design System',
    html: themeHtml,
  },
};

module.exports = { themePage };
