function section(number, label, title, description, body) {
  return `<section class="section"><div class="section-head"><div><span class="section-no">${number} / ${label}</span><h2>${title}</h2></div><p>${description}</p></div>${body}</section>`;
}

const themeHtml = `<main class="page docs-page">
<header class="page-head"><div><span class="eyebrow">CIIMO / marca / tema</span><h1>Light e Dark.</h1><p>Os dois temas usam a mesma identidade CIIMO. O verde oficial permanece intacto como cor de marca; no Light, um papel semântico mais escuro é usado quando o verde precisa funcionar como texto, ícone, foco ou estado sobre superfície clara.</p></div><div class="page-index">01 — Princípio<br>02 — Tokens<br>03 — Contraste<br>04 — Marca<br>05 — Comportamento</div></header>
${section('01', 'Princípio', 'Dois temas, uma identidade', 'Dark continua sendo a apresentação padrão. Light é uma variante completa de superfície e contraste, não uma inversão automática.', `<div class="theme-preview-grid"><article class="theme-preview theme-preview--dark"><span class="eyebrow">DARK</span><img src="../assets/brand/ciimo_cw.svg" alt="CIIMO branca com II verde"><div class="theme-preview__surface"><small>Carteira</small><strong>R$ 4,02 mi</strong><span class="accent-content">+12,8% de valorização</span></div></article><article class="theme-preview theme-preview--light"><span class="eyebrow">LIGHT</span><img src="../assets/brand/ciimo_cb.svg" alt="CIIMO preta com II verde"><div class="theme-preview__surface"><small>Carteira</small><strong>R$ 4,02 mi</strong><span class="accent-content">+12,8% de valorização</span></div></article></div>`)}
${section('02', 'Tokens', 'Marca e conteúdo não usam o mesmo papel', 'O lime oficial não muda. A diferença está no papel semântico usado quando a própria cor precisa carregar informação legível.', `<div class="table-wrap"><table><thead><tr><th>Token</th><th>Dark</th><th>Light</th><th>Uso</th></tr></thead><tbody><tr><td><strong>background</strong></td><td>#000000</td><td>#F4F1EA</td><td>Canvas principal</td></tr><tr><td><strong>surface</strong></td><td>#0B0B0B</td><td>#FFFFFF</td><td>Cards e blocos principais</td></tr><tr><td><strong>text</strong></td><td>#F4F1EA</td><td>#111111</td><td>Texto principal</td></tr><tr><td><strong>muted</strong></td><td>rgba(244,241,234,.72)</td><td>rgba(17,17,17,.68)</td><td>Texto secundário</td></tr><tr><td><strong>accent</strong></td><td>#D4FB00</td><td>#D4FB00</td><td>Marca, fundo de CTA e seleção preenchida</td></tr><tr><td><strong>accent-content</strong></td><td>#D4FB00</td><td>#5B6C00</td><td>Texto, ícone, foco e estado sobre superfície neutra</td></tr><tr><td><strong>accent-text</strong></td><td>#050505</td><td>#050505</td><td>Texto sobre fundo lime</td></tr></tbody></table></div>`)}
${section('03', 'Contraste', 'Lime não vira texto no Light', 'Em superfícies claras, #D4FB00 continua sendo a assinatura da marca, mas não é usado como cor de conteúdo. O verde #5B6C00 mantém a direção cromática e oferece contraste acima de 5:1 tanto sobre o canvas claro quanto sobre branco.', `<div class="grid grid-3"><article class="specimen"><span class="variant-title">Marca</span><div style="width:56px;height:56px;border-radius:14px;background:#D4FB00;margin:16px 0"></div><h3>#D4FB00</h3><p>Logo, CTA primário e seleção preenchida.</p></article><article class="specimen"><span class="variant-title">Conteúdo / Light</span><div style="width:56px;height:56px;border-radius:14px;background:#5B6C00;margin:16px 0"></div><h3 class="accent-content">#5B6C00</h3><p>Links ativos, ícones, foco e indicadores.</p></article><article class="specimen"><span class="variant-title">Regra</span><h3>Cor de marca ≠ cor de texto</h3><p>Escolha o papel pelo contexto de contraste, sem recolorir a identidade oficial.</p></article></div>`)}
${section('04', 'Marca', 'SVG correto para cada contraste', 'Os arquivos-mestre são usados diretamente. Não aplicar filter, invert ou recoloração via CSS no logotipo.', `<div class="grid grid-2"><article class="specimen"><span class="variant-title">Dark</span><h3>Assinatura</h3><code>ciimo_cw.svg</code><h3 style="margin-top:16px">Símbolo compacto</h3><code>ii_v.svg</code></article><article class="specimen"><span class="variant-title">Light</span><h3>Assinatura</h3><code>ciimo_cb.svg</code><h3 style="margin-top:16px">Símbolo compacto</h3><code>ii_b.svg</code></article></div>`)}
${section('05', 'Comportamento', 'Preferência e contraste persistem entre rotas', 'A troca acontece no shell independente da sidebar. Os componentes continuam os mesmos; apenas os tokens semânticos mudam.', `<div class="icon-rule-list"><div><strong>Padrão inicial</strong><span>Dark quando ainda não existe preferência salva.</span></div><div><strong>Persistência</strong><span><code>localStorage["ciimo-theme"]</code> com <code>dark</code> ou <code>light</code>.</span></div><div><strong>Conteúdo verde</strong><span>Usa <code>--accent-content</code>, nunca <code>--accent</code> diretamente.</span></div><div><strong>CTA preenchido</strong><span>Continua usando <code>--accent</code> com <code>--accent-text</code>.</span></div><div><strong>Regra</strong><span>Qualquer nova superfície deve ser validada nos dois temas no mesmo commit.</span></div></div>`)}
</main>`;

const themePage = {
  route: 'brand/theme.html',
  page: {
    title: 'Tema claro e escuro · CIIMO Design System',
    html: themeHtml,
  },
};

module.exports = { themePage };
