function section(number, label, title, description, body) {
  return `<section class="section"><div class="section-head"><div><span class="section-no">${number} / ${label}</span><h2>${title}</h2></div><p>${description}</p></div>${body}</section>`;
}

const themeHtml = `<main class="page docs-page">
<header class="page-head"><div><span class="eyebrow">CIIMO / marca / tema</span><h1>Light e Dark.</h1><p>Os dois temas usam a mesma identidade CIIMO. No Dark, o lime original permanece como accent principal. No Light, #AFC728 passa a ser a cor principal da interface para ganhar presença sobre superfícies claras; quando o verde precisa carregar texto, ícone, foco ou estado, o sistema continua usando um papel semântico mais escuro.</p></div><div class="page-index">01 — Princípio<br>02 — Tokens<br>03 — Contraste<br>04 — Marca<br>05 — Comportamento</div></header>
${section('01', 'Princípio', 'Dois temas, uma identidade', 'Dark continua sendo a apresentação padrão. Light é uma variante completa de superfície e contraste, não uma inversão automática.', `<div class="theme-preview-grid"><article class="theme-preview theme-preview--dark"><span class="eyebrow">DARK</span><img src="../assets/brand/ciimo_cw.svg" alt="CIIMO branca com II verde"><div class="theme-preview__surface"><small>Carteira</small><strong>R$ 4,02 mi</strong><span class="accent-content">+12,8% de valorização</span></div></article><article class="theme-preview theme-preview--light"><span class="eyebrow">LIGHT</span><img src="../assets/brand/ciimo_cb.svg" alt="CIIMO preta com II verde"><div class="theme-preview__surface"><small>Carteira</small><strong>R$ 4,02 mi</strong><span class="accent-content">+12,8% de valorização</span></div></article></div>`)}
${section('02', 'Tokens', 'Accent de interface e conteúdo têm papéis diferentes', 'O tema muda o accent principal da interface, mas preserva um verde mais escuro quando a própria cor precisa carregar informação legível.', `<div class="table-wrap"><table><thead><tr><th>Token</th><th>Dark</th><th>Light</th><th>Uso</th></tr></thead><tbody><tr><td><strong>background</strong></td><td>#000000</td><td>#F4F1EA</td><td>Canvas principal</td></tr><tr><td><strong>surface</strong></td><td>#0B0B0B</td><td>#FFFFFF</td><td>Cards e blocos principais</td></tr><tr><td><strong>text</strong></td><td>#F4F1EA</td><td>#111111</td><td>Texto principal</td></tr><tr><td><strong>muted</strong></td><td>rgba(244,241,234,.72)</td><td>rgba(17,17,17,.68)</td><td>Texto secundário</td></tr><tr><td><strong>accent</strong></td><td>#D4FB00</td><td>#AFC728</td><td>CTA, seleção preenchida, gráficos e destaque principal</td></tr><tr><td><strong>accent-content</strong></td><td>#D4FB00</td><td>#5B6C00</td><td>Texto, ícone, foco e estado sobre superfície neutra</td></tr><tr><td><strong>accent-text</strong></td><td>#050505</td><td>#050505</td><td>Texto sobre fundo de accent</td></tr></tbody></table></div>`)}
${section('03', 'Contraste', 'No Light, presença e legibilidade usam verdes diferentes', '#AFC728 é a cor principal da interface clara porque se separa melhor das superfícies claras do que o lime original. Para texto e ícones, #5B6C00 continua sendo necessário porque oferece contraste de leitura superior.', `<div class="grid grid-3"><article class="specimen"><span class="variant-title">Dark / identidade</span><div style="width:56px;height:56px;border-radius:14px;background:#D4FB00;margin:16px 0"></div><h3>#D4FB00</h3><p>Accent principal no Dark e cor presente nos SVGs oficiais.</p></article><article class="specimen"><span class="variant-title">Principal / Light</span><div style="width:56px;height:56px;border-radius:14px;background:#AFC728;margin:16px 0"></div><h3>#AFC728</h3><p>CTA, seleção preenchida, barras, áreas e destaques principais.</p></article><article class="specimen"><span class="variant-title">Conteúdo / Light</span><div style="width:56px;height:56px;border-radius:14px;background:#5B6C00;margin:16px 0"></div><h3 class="accent-content">#5B6C00</h3><p>Texto, ícone, foco e indicadores sobre superfícies claras.</p></article></div>`)}
${section('04', 'Marca', 'SVG correto para cada contraste', 'Os arquivos-mestre são usados diretamente. Não aplicar filter, invert ou recoloração via CSS no logotipo. A mudança do accent do Light é uma decisão de interface e não altera os SVGs oficiais.', `<div class="grid grid-2"><article class="specimen"><span class="variant-title">Dark</span><h3>Assinatura</h3><code>ciimo_cw.svg</code><h3 style="margin-top:16px">Símbolo compacto</h3><code>ii_v.svg</code></article><article class="specimen"><span class="variant-title">Light</span><h3>Assinatura</h3><code>ciimo_cb.svg</code><h3 style="margin-top:16px">Símbolo compacto</h3><code>ii_b.svg</code></article></div>`)}
${section('05', 'Comportamento', 'Preferência e contraste persistem entre rotas', 'A troca acontece no shell independente da sidebar. Os componentes continuam os mesmos; apenas os tokens semânticos mudam.', `<div class="icon-rule-list"><div><strong>Padrão inicial</strong><span>Dark quando ainda não existe preferência salva.</span></div><div><strong>Persistência</strong><span><code>localStorage["ciimo-theme"]</code> com <code>dark</code> ou <code>light</code>.</span></div><div><strong>Accent preenchido</strong><span><code>--accent</code>: #D4FB00 no Dark e #AFC728 no Light.</span></div><div><strong>Conteúdo verde</strong><span>Usa <code>--accent-content</code>; no Light permanece #5B6C00.</span></div><div><strong>CTA preenchido</strong><span>Usa <code>--accent</code> com <code>--accent-text</code>.</span></div><div><strong>Regra</strong><span>Qualquer nova superfície deve ser validada nos dois temas no mesmo commit.</span></div></div>`)}
</main>`;

const themePage = {
  route: 'brand/theme.html',
  page: {
    title: 'Tema claro e escuro · CIIMO Design System',
    html: themeHtml,
  },
};

module.exports = { themePage };
